konveyor/operator

roles/tackle/templates/deployment-ui.yml.j2

UI is not using Nginx anymore and the deployment will constantly kill the ui pod because the probe would fail.

UI Probe for node instead of nginx

---

roles/tackle/defaults/main.yml
roles/tackle/templates/deployment-hub.yml.j2

- Fixes #11
- Add ADDON_WORKING_DIR , defaults to /working
- Operator only adds the ENV variable, Hub will have to handle mounting/creating the directory

HUB: Set ADDON_WORKING_DIR on deployment

---

roles/tackle/defaults/main.yml
roles/tackle/templates/deployment-keycloak-sso.yml.j2

- Add JAVA_OPTS to keycloak SSO deployment , operator variable keycloak_sso_java_opts
- Default keycloak_sso_java_opts to "-Dcom.redhat.fips=false"
- Fixes #26

Add JAVA_OPTS to sso deployment

---

roles/tackle/defaults/main.yml
roles/tackle/templates/deployment-keycloak-sso.yml.j2

Allow a user to manipulate init delay (in seconds) via operator for the keycloak deployment, liveness or readiness via these Tackle CR spec vars:
keycloak_sso_liveness_init_delay: "xx"
keycloak_sso_readiness_init_delay: "xx"
This should help in cases where system performance is a considerable factor during keycloak start up.

Parametize keycloak init delay

---

roles/tackle/templates/configmap-keycloak-sso.yml.j2

* Add `admin` user with a temporary password that has `admin` (used by Pathfinder) and `tackle-admin` roles.
* Remove write permissions on proxies/identities/settings from the `tackle-architect` role.
* Add `adoptionplans:post` scope to all tackle roles.

Realm improvements

---

roles/tackle/defaults/main.yml
roles/tackle/templates/deployment-hub.yml.j2

- Fixes #47
- Only hub_task_sa task is defined and set by default to tackle-hub
- hub_task_reap_created, hub_task_reap_succeeded, hub_task_reap_failed
and hub_task_retries only apply when they are defined on the CR

Hub: Add support for reaper settings

---

roles/tackle/templates/deployment-keycloak-sso.yml.j2

Currently we use a busybox image which calls wget to obtain theme .jar file and inject it into a volume for keycloak use , this new image based approach does the same but has the advantage in proxy configurations where sites might not allow to download files directly , only images.

Keycloak: Use init container image instead of busybox

---

roles/tackle/templates/configmap-keycloak-sso.yml.j2

Adding password format requirement to the Keycloak initial Tackle realm configuration.
Proposal to a valid password format is to:
- have minimal length 8 chars
- contain at least 1 uppercase letter
- contain at least 1 lowercase letter
- contain at least 1 digit
**The password format could be discussed in reviews.**
More possible options are in Keycloak docs:https://github.com/keycloak/keycloak-documentation/blob/main/server_admin/topics/authentication/password-policies.adoc
https://issues.redhat.com/browse/TACKLE-522

Specify Keycloak User password format

---

roles/tackle/tasks/main.yml

- Allow PG pods to be in running state before continuing deployment of
keycloak and pathfinder
- Fixes race issues when PG is not yet forwarding traffic while other
applications are trying to access during start-up

Wait for PG deployments to be in running state

---

tools/tackle_cleanup.sh

- Allow handling of kubernetes/minikube cluster cleanups
Usage:
```
./tackle_cleanup.sh -h
Valid options for tackle_cleanup.sh: 
-o : OpenShift cleanup
-k : Kubernetes cleanup
-h : Print help
```

Enhance tackle_cleanup script

---

roles/tackle/defaults/main.yml

- Drop default from 1 core to 500m

Decrease resource request for windup addon

---

tools/cut-release.py
tools/templates/annotations.yaml.j2
tools/templates/bundle.Dockerfile.j2
tools/templates/clusterserviceversion.yaml.j2
tools/templates/tackle-k8s.yaml.j2

- Python tools to re-template all necessary files in order to cut new
releases upstream
Usage:
```
usage: cut-release.py [-h] --version VERSION [--release_prefix RELEASE_PREFIX] [--channel CHANNEL] [--templates-path TEMPLATES_PATH]
[--project-path PROJECT_PATH]
Prepare a new Tackle project release
optional arguments:
-h, --help            show this help message and exit
--version VERSION     version must follow semver format (i.e 2.0.0) unless latest
--release_prefix RELEASE_PREFIX
release_prefix is the scheme used for branching project (i.e release-v), default is v
--channel CHANNEL     OLM channel must follow semver format (i.e release-v2.0), if not supplied will be derived to X.Y from version
--templates-path TEMPLATES_PATH
Absolute path to directory containing jinja2 templates, …
```

Add operator release automation tools

---

roles/tackle/defaults/main.yml
roles/tackle/templates/ingress-ui.yml.j2

- proxy-body-size to 500m to prevent issues with binary uploads in k8s clusters

Set proxy-body-size default on ingress k8s controllers

---

README.md
bundle/manifests/tackle-operator.clusterserviceversion.yaml
roles/tackle/defaults/main.yml
roles/tackle/tasks/main.yml
roles/tackle/templates/deployment-hub.yml.j2
roles/tackle/templates/deployment-keycloak-postgresql.yml.j2
roles/tackle/templates/deployment-keycloak-sso.yml.j2
roles/tackle/templates/deployment-pathfinder-postgresql.yml.j2
roles/tackle/templates/deployment-pathfinder.yml.j2
roles/tackle/templates/deployment-ui.yml.j2
roles/tackle/templates/ingress-ui.yml.j2
roles/tackle/templates/networkpolicy.yml.j2
roles/tackle/templates/route-ui.yml.j2

- Implement namespace isolation via network policies, by default feature is turned on. OCP has support for network policies by default in OpenShift SDN , in k8s clusters calico can be installed
- Policy allows ingress traffic to all ports from any pod that lives in the Tackle namespace, blocks all other ingress traffic
- Enforcement of policy via immutable namespace label kubernetes.io/metadata.name=<namespace>
- If the cluster lacks support for k8s network policies , the policy will not have any effect
- Bumped minKubeVersion to v1.22.0 for network policy feature compatibility
- Tested on OCP v4.10 and minikube v1.24 w/ calico

Allow namespace isolation via network policies

---

roles/tackle/templates/networkpolicy.yml.j2

**Network policy updates**
* tackle-default-deny : explicitly denies all ingress traffic to all pods in tackle namespace from any source
* tackle-namespace : allows ingress traffic from any pod in the tackle namespace to all ports
* tackle-external : allows ingress traffic from any pod to the tackle UI pod on ports 8080 and 8443
I have left the feature namespace isolation off by default until the policy gets more mileage.

Allow external UI access via network policy

---

roles/tackle/templates/deployment-hub.yml.j2
roles/tackle/templates/deployment-ui.yml.j2

Needed by the Hub.  No longer used by the UI.
Needs to be coordinated with hub and UI PRs.

PATHFINDER_URL moved to hub.

---

bundle/manifests/tackle-operator.clusterserviceversion.yaml

- Incorrect API group causes OCP web console to fail to render with an
error message

Fix operator details page in OCP web console

---

bundle/manifests/tackle-operator.clusterserviceversion.yaml
roles/tackle/defaults/main.yml
tools/templates/clusterserviceversion.yaml.j2

- Rename image environmental vars to comply with OSBS SHA pinning naming scheme
- Requires re-deployment as operator and OLM metadata has changed

Rename component image ENV vars

---

.github/actions/install-tackle/action.yml
.github/actions/start-minikube/action.yml
Makefile
hack/install-tackle.sh
hack/start-minikube.sh

This is the first PR with the goal leveraging GitHub Actions to provide the Konveyor organization with a simple and extensible CI/CD platform. Here is a [link to the Google Slides](https://docs.google.com/presentation/d/1l9BObaU7tSO9OXQw5CCs_ziyJIexw6qxZi-o2wRtNVc) where this was presented in the [Konveyor Technical Architecture Forum](https://docs.google.com/document/d/1Z_i9Qzxn8GST5b6aU_-IUBY4fcd13YCwCsfEqOnAff8/edit#heading=h.ddgaq7lqxzdk).
**tl;dr**
* This PR introduces 2 GitHub Actions (`start-minikube` and `install-tackle`)
* These actions are run via shell scripts that can be invoked via Makefile for local development
* Shell scripts are intentionally made to be self-contained (no `source utils.sh`) and idempotent (`kubectl apply` instead of `kubectl create`) to make them useful …

ci(actions): start minikube & install tackle

---

bundle/manifests/tackle-operator.clusterserviceversion.yaml
roles/tackle/defaults/main.yml
roles/tackle/templates/deployment-hub.yml.j2
roles/tackle/templates/deployment-ui.yml.j2
tools/templates/clusterserviceversion.yaml.j2

This PR should aid Tackle components to identify what profile and version of Tackle is deployed, this allows us to act accordingly to different use cases, (i.e upstream or downstream). The operator will expose environment variables to UI and HUB pods as PROFILE and VERSION. The authoritative source for these values is the Operator Bundle CSV.
Summary of changes below:
- PROFILE and VERSION defined in the Operator CSV and sourced by ansible operator as app_profile and app_version
- Valid values for PROFILE are **konveyor** or **mta** , default value for Tackle is **konveyor**.
- Tackle release tools also updated to account for these new environmental vars

Implement PROFILE and VERSION

---

bundle/manifests/tackle-operator.clusterserviceversion.yaml
tools/templates/clusterserviceversion.yaml.j2

- Align upstream keycloak release with RHSSO 7.6 (based on v18)
- Targeted for 2.1.2
References in RHSSO 7.6 announcement : 
[RHSSO 7.6](https://access.redhat.com/announcements/6965643)

Upgrade keycloak to v18

---

bundle/manifests/tackle-operator.clusterserviceversion.yaml
roles/tackle/defaults/main.yml
roles/tackle/tasks/main.yml
roles/tackle/templates/configmap-trusted-ca.yml.j2
roles/tackle/templates/deployment-ui.yml.j2

PR Summary:
- Add NODE_EXTRA_CA_CERTS environment var to UI deployment pod for nodejs consumption of CA bundle
- Add support for custom ingress CA certificates if they are present in OpenShift
- Related to https://github.com/konveyor/tackle2-ui/pull/447
- Target 2.1.2 release

Add NODE_EXTRA_CA_CERTS support to UI deployment

---

roles/tackle/templates/customresource-addon-windup.yml.j2

The windup addon image pull policy is now controlled by the global image_pull_policy parameter in the Tackle CR. 
This addresses possible inconsistencies between the windup addon pull policy and the rest of Tackle components.

Windup addon ensure image pull policy is set

---

roles/tackle/tasks/main.yml

The windup addon (or any other addon for this matter), should always be reconciled to avoid stale data , such as a old addon image reference or to also honor Tackle CR settings such as image pull policy or resource requests.
This is specially impactful during Tackle upgrades, see : https://issues.redhat.com/browse/MTA-127
This PR removes the set and forget task by operator and forces to reconcile in every cycle.

Ensure windup addon is always reconciled

---

bundle/manifests/tackle-operator.clusterserviceversion.yaml
roles/tackle/tasks/main.yml
roles/tackle/templates/customresource-rhsso-keycloak.yml.j2
roles/tackle/templates/deployment-hub.yml.j2
roles/tackle/templates/secret-keycloak-db.yml.j2

These changes are intended to switch us from using a postgresql container provisioned by the RHSSO operator which is unsupported and uses a tag making it impossible to use MTA in a disconnected cluster (without enabling an experimental feature to allow mirroring with tags).
The operator will cleanly switch the operator to use a postgresql database container provisioned by us, but it will not migrate data. Users will be required to log back with the default password and reconfigure any users they have created.
~~Up to this point as far as I can tell RHSSO does not appear to deprovision its postgresql deployment when the configuration is changed to use an 'external' database and the keycloak-discovery service never becomes ready, so for an upgrade these manual steps are currently required. …

:bug: Manage DB container for RHSSO

---

roles/tackle/tasks/main.yml

When not coming from an upgrade situation the Deployment array in secondary resources doesn't exist and it causes a reconcile failure.

:bug: Fix keycloak deployment check

---

roles/tackle/tasks/main.yml

When not coming from an upgrade situation the Deployment array in secondary resources doesn't exist and it causes a reconcile failure.

:bug: Fix keycloak deployment check (#162)

---

roles/tackle/templates/persistentvolumeclaim-cache.yml.j2
roles/tackle/templates/persistentvolumeclaim-hub-bucket.yml.j2
roles/tackle/templates/persistentvolumeclaim-hub-database.yml.j2
roles/tackle/templates/persistentvolumeclaim-keycloak-postgresql.yml.j2
roles/tackle/templates/persistentvolumeclaim-pathfinder-postgresql.yml.j2

Setting an empty storageClassName can result in failure for the default storage class provisioner to provision the PVC.
This was observed on a GCP cluster @rayfordj was test on.
```
$ oc describe pvc mta-hub-bucket-volume-claim
Name:          mta-hub-bucket-volume-claim
Namespace:     openshift-mta
StorageClass:  
Status:        Pending
Volume:        
Labels:        app.kubernetes.io/component=hub
app.kubernetes.io/name=mta-hub
app.kubernetes.io/part-of=mta
volume=mta-hub-bucket
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       mta-hub-96dc6ff9d-cbn5k
Events:
Type    Reason         Age                  From                         Message
----    ------         ----                 ---- …
```

:bug: Don't set an empty storageClassName when not set

---

bundle/manifests/tackle-operator.clusterserviceversion.yaml
roles/tackle/defaults/main.yml

Requested that konveyor not require auth by default.

:sparkles: Make feature_auth_required false by default

---

.github/workflows/create-release.yml

We can't use GitHub's automatic token if 1) we want to create releases in other repositories (ie. operator creating a release in the hub) and 2) we want the publish steps to run in those repos.

:seedling: create-release workflow should pass token

---

.github/workflows/create-release.yml

In addition to adding the remainder of the projects we are concerned with. This also includes a "wait" for each of the images to be published. We can later use this as our gate for the publish step.

:seedling: create-release: Add remaining projects

---

docs/installation-macos.md

Following the install guide as-is throws an error while starting minikube. To solve the error, this PR adjusts the memory limit for minikube to be a little less than podman.

:bug: Update memory limit for minikube start command in the documentation

---

roles/tackle/templates/deployment-keycloak-postgresql.yml.j2
roles/tackle/templates/deployment-pathfinder-postgresql.yml.j2

On EKS and probably other kubernetes variants the PostgreSQL pods run as user 26. Without setting the fsGroup the storage is mounted 755 owned by root:root so postgres can't write and fails to start with a permission denied.
26 comes from the Dockerfile the image is built with https://github.com/sclorg/postgresql-container/blob/master/12/Dockerfile.centos7#L88

:bug: Set fsGroup for non-OpenShift clusters

---

Makefile

I ran into issues building on mac and having the Makefile honor the alias docker=podman

:seedling: Allow overriding to use podman instead of docker in Makefile

---

tackle-k8s-dev.yaml

The [tools/tackle-opdev.sh](https://github.com/konveyor/tackle2-operator/blob/main/tools/tackle-opdev.sh#L155) script uses this for dev workflows
I think this needs to updated for the konveyor-operator rename.

:seedling: Updated for konveyor-operator name change for dev workflow

---

bundle/manifests/konveyor-operator.clusterserviceversion.yaml
roles/tackle/defaults/main.yml
roles/tackle/tasks/main.yml
roles/tackle/templates/deployment-hub.yml.j2
roles/tackle/templates/deployment-ui.yml.j2
roles/tackle/templates/route-ui.yml.j2
roles/tackle/templates/secret-cookie-secret.yml.j2
roles/tackle/templates/service-ui.yml.j2
roles/tackle/templates/serviceaccount-ui.yml.j2

WIP. Need to test downstream and turning auth on and off and switching a little more.
Right now I've switched from keycloak -> oauth without issue.
Could use clean up around conditionals in templates as well. These should be possible to make smaller and cleaner.

:sparkles: Provide openshift-oauth as an authentication option

---

Makefile
tools/tackle-opdev.sh

With these changes I'm able to locally build on my arm64 Mac and deploy the images onto my EKS cluster (amd64).
Needed to address 2 issues:
1. Allow --arch amd64 to be passed into image builds in Makefile
2. Account for "sed -i" difference on Mac vs Linux

:seedling: Updates to build on mac arm64 and deploy to amd64

---

hack/install-tackle.sh
roles/tackle/defaults/main.yml
roles/tackle/tasks/main.yml
roles/tackle/templates/ingress-ui.yml.j2
tools/tackle-opdev.sh

Fixes #184 
Fixes #167 (confirmed working with `feature_auth_required: true`)
Relates to #170
These changes allow us to deploy Konveyor onto an Amazon EKS cluster that uses the Amazon recommended Amazon Load Balancer ingress opposed to 'nginx'. 
I deployed the EKS cluster for testing using this newly developed automation:
https://github.com/konveyor/hack_env_helpers/tree/main/aws/eks
I captured notes while exploring ALB Ingress here for debugging purposes:
https://gist.github.com/jwmatthews/d492a4944c83dc3f2d016187d53d13b2

:sparkles: Support for Amazon Load Balancer Ingress controller

---

roles/tackle/defaults/main.yml

Default behavior should be to not use RWX since it's least common.

:sparkles: Make rwx_supported false by default

---

tools/konveyor-operator-publish-commands.sh

We're creating an extra nested konveyor-operator directory when copying the operator files for the k8s community operators. https://github.com/k8s-operatorhub/community-operators/pull/2729
I believe this should fix it.

:ghost: Remove the extra nested dir when copying to operatorhub-io

---

tools/konveyor-operator-publish-commands.sh

The label being added after  the K8S PR is submitted is not relevant to K8S, but it seems fine for the LABEL to be present in on the operator, as it exists on many others.
https://github.com/search?q=repo%3Ak8s-operatorhub%2Fcommunity-operators%20com.redhat.openshift.versions&type=code
The current flow results in the LABEL being added to the prior version when we submit a new PR, which just looks odd and is probably confusing. Flipping the order should change it to be included on the current version from now on and preventing the strange behavior going forward _after_ the next version is added.

:ghost: Make last edit before submitting k8s PR.

---

.ansible-lint-ignore
roles/tackle/defaults/main.yml
roles/tackle/tasks/main.yml

This will prevent the playbook from failing when Keycloak is disabled because it is unable to find the Keycloak kind.
Closes #219
I also added skips for the var-naming role prefix ansible-lint rule as that was failing and is not related to this PR

:bug: Guard references to Keycloak

---

bundle/manifests/konveyor-operator.clusterserviceversion.yaml
config/rbac/role.yaml
roles/tackle/tasks/main.yml
roles/tackle/templates/networkpolicy.yml.j2
roles/tackle/templates/servicemonitor-hub.yml.j2
tools/templates/clusterserviceversion.yaml.j2

* Adds a ServiceMonitor to allow the in-cluster monitoring to scrape Hub metrics (requires an OpenShift cluster)
* Adds a NetworkPolicy to expose the Hub's metrics port.
* Adds RBAC roles to allow the operator to manage ServiceMonitors
I'm not sure if there's a better way to test if the monitoring operator is available, or if there's a way to more tightly restrict the network policy.
I'll need to backport this to release-0.2 once it is merged.
Related to https://issues.redhat.com/projects/MTA/issues/MTA-402

:sparkles: Add ServiceMonitor for hub metrics

---

bundle/manifests/konveyor-operator.clusterserviceversion.yaml
roles/tackle/tasks/main.yml
roles/tackle/templates/networkpolicy.yml.j2
roles/tackle/templates/servicemonitor-hub.yml.j2
tools/templates/clusterserviceversion.yaml.j2

* Adds a ServiceMonitor to allow the in-cluster monitoring to scrape Hub metrics (requires an OpenShift cluster)
* Adds a NetworkPolicy to expose the Hub's metrics port.
* Adds RBAC roles to allow the operator to manage ServiceMonitors
I'm not sure if there's a better way to test if the monitoring operator is available, or if there's a way to more tightly restrict the network policy.
Related to https://issues.redhat.com/projects/MTA/issues/MTA-402

[backport] :sparkles: Add ServiceMonitor for hub metrics (#242)

---

.github/workflows/create-release.yml

When pushing our manifests to k8s/openshift community-operators, we should do so from the release branch instead of `main`.

:seedling: Publish from branch

---

.github/workflows/create-release.yml

Even though the project has changed to konveyor/operator, the image we push to quay (at least for now) is konveyor/tackle2-operator.

:seedling: Keep operator name the same

---

hack/install-tackle.sh

The Tackle/Konveyor install script has few waiting loops checking the installation progress/completeness. Based on last few errors, adding an output with tackle details when waiting loop timeouted to help with debugging CI errors directly in github workflow execution.
Example with recent installation error:
```
...
error: timed out waiting for the condition on tackles/tackle
...
status:
conditions:
- lastTransitionTime: "2023-07-24T08:51:07Z"
message: ""
reason: ""
status: "False"
type: Successful
- ansibleResult:
changed: 0
completion: 2023-07-24T09:05:50.668218
failures: 1
ok: 14
skipped: 48
lastTransitionTime: "2023-07-24T09:05:51Z"
message: |
The task includes an option with an undefined variable. The error was: 'hub_seed_configmap_name' is undefined
The error appears to be in …
```

:seedling: Update install script with debug output

---

.github/workflows/create-release.yml
.github/workflows/pr-checks.yml

Since we usually provide the "previous_version" as input to the workflow, we should just pass it along to the create release action to prevent us from having to be clever.

:seedling: use previous version when creating release

---

tools/upgrades/migrate-pathfinder-assessments.py

Since Pathfinder component is being replaced by Konveyor Hub API, already existing Assessments need to be migrated. Adding a script based on Hub's CLI tool https://github.com/konveyor/tackle2-hub/tree/main/hack/tool that connects to running Pathfinder and migrates Assessments to running Hub API v0.3.
This script is expected to be executed by operator during upgrade Konveyor 0.2->0.3.
Example usage: (only auth token argument is optional, both urls are required)
```
$ ./migrate-pathfinder-assessments --pathfinder-url http://pathfinder.svc --hub-base-url http://hub.svc:8080 --token ""
```
Related to https://github.com/konveyor/tackle2-hub/issues/489 and https://github.com/konveyor/tackle2-hub/pull/507

:seedling: Add Pathfinder Assessments migration script

---

roles/tackle/defaults/main.yml
roles/tackle/templates/deployment-hub.yml.j2

Intended to resolve https://issues.redhat.com/browse/MTA-849

:sparkles: Pass proxy configuration through to Hub pod

---

.github/actions/install-konveyor/action.yml
.github/actions/make-bundle/action.yml
Makefile

remove the `deploy-olm` target entirely in favor of the `install` and `uninstall` targets for development.

:ghost: target specific variables not working

---

roles/tackle/defaults/main.yml

Deploying the pod with request = limit should be a good (incremental) step towards preventing OOM kills.
My memory profiling suggests that 4Gi is a good number for our TestApp.  Although, I can run analysis on the TestApp using 2Gi/2Gi just fine (though memory peaks at 1.9Gi) on my minikube but Pranav reports that he cannot.
We should still follow up with passing -Xmx=80% of limit to the Java provider.
IMHO, 4Gi is much higher than I would have expected for the analyzer.  This means that when running on most personal, single node clusters (like minikube), we will only be able to analyze a few applications in parallel.

:bug: Addon memory request and limit match.

---

Dockerfile

CentOS Stream 8 is EOL. For the short term we can still get packages from the CentOS vault.

:ghost: Fix build failures

---

.github/workflows/march-image-build-push.yml

build-push-quay is doing a clean checkout so what we do before has no bearing.

:bug: Move index Dockerfile generation to pre_build_cmd

---

bundle/manifests/konveyor-operator.clusterserviceversion.yaml
helm/templates/olm/konveyor-operator.clusterserviceversion.yaml

I have admittedly not tested extensively, but we can install and the UI comes up. Dependencies are also far less problematic on arm64 than ppc64le and s390x. However, the operator does not show up on arm64 clusters, I _think_ because we are missing these labels.

:ghost: Add Architecture support labels

---

docs/installation-macos.md

v0.21.2 fails on Apple Silicon ARM due to this https://github.com/operator-framework/operator-lifecycle-manager/issues/2823#issuecomment-1468421055
A minimum of 0.24.0 is required, I managed to install it on my machine with 0.27.0

:book: Update OLM version in installation-macos.md

---

.github/workflows/pr-ci.yml

This should make "rerunning failed" tasks in workflows less likely to fail simply because the image didn't exist anymore.

:seedling: double the ttl on operator image

---

.github/workflows/pr-ci.yml

:seedling: must build whole bundle for operator ci

---

bundle/manifests/konveyor-operator.clusterserviceversion.yaml
helm/templates/olm/konveyor-operator.clusterserviceversion.yaml

I am not certain about this one. Can others weigh in:
```
features.operators.openshift.io/proxy-aware
Specify whether an Operator supports running on a cluster behind a proxy by accepting the standard HTTP_PROXY and HTTPS_PROXY proxy environment variables. If applicable, the Operator passes this information to the workload it manages (operands).
```

:ghost: Add CSV annotations

---

konveyor-operator-catalog.yaml

This was accidentally updated by a change for testing that slipped in.

:bug: Correct catalog source image name

---

README.md
roles/tackle/defaults/main.yml
roles/tackle/templates/deployment-hub.yml.j2

This is necessary for Kai to harvest historical data from the hub
Related to konveyor/tackle2-hub/pull/631

:sparkles: Add setting to disable analysis archiver

---

roles/tackle/templates/customresource-addon-language-discovery.yml.j2
roles/tackle/templates/customresource-addon-tech-discovery.yml.j2

system generated tasks should run at default priority (0).

:bug: discovery should run at default priority.

---

roles/tackle/templates/customresource-addon-language-discovery.yml.j2
roles/tackle/templates/customresource-addon-tech-discovery.yml.j2

system generated tasks should run at default priority (0).

:bug: discovery should run at default priority. (#346)

---

Dockerfile
roles/tackle/tasks/main.yml
roles/tackle/templates/deployment-keycloak-postgresql.yml.j2
roles/tackle/templates/service-keycloak-postgresql-migration.yml.j2
roles/tackle/templates/service-keycloak-postgresql.yml.j2

When using psql, errors in applying the sql generated from the dump do not reach bash without adding additional options. psql only generates a non-zero exit code when something fatal happens, like being unable to connect to the database host. So, all ansible sees is exit code 0 from psql and continues on, as if everything is great.
I did some reading up on postgres modules for ansible and we do not need to shell out to do this, so I have implemented it with modules.
Since handling the actual migration with the ansible modules I have not encountered a failure. Continuing to run upgrades to test ...

:bug: Use postgresql modules for migration

---

bundle/manifests/konveyor-operator.clusterserviceversion.yaml
helm/templates/deployment.yaml
helm/values.yaml
roles/tackle/defaults/main.yml
roles/tackle/tasks/kai.yml
roles/tackle/tasks/main.yml
roles/tackle/templates/kai/kai-api-deployment.yaml.j2
roles/tackle/templates/kai/kai-api-service.yaml.j2
roles/tackle/templates/kai/kai-config.yaml.j2
roles/tackle/templates/kai/kai-db-deployment.yaml.j2
roles/tackle/templates/kai/kai-db-pvc.yaml.j2
roles/tackle/templates/kai/kai-db-service.yaml.j2
roles/tackle/templates/kai/kai-importer-deployment.yaml.j2
roles/tackle/templates/kai/kai-importer-service.yaml.j2

Adds experimental support for deploying kai alongside konveyor in hub-importer mode. Prerequisite to run is creating a secret with the LLM credentials in it.
`kubectl create secret -n konveyor generic kai-api-key-secret --fromliteral=genai_key=[BAM_KEY] --from-literal=api_base=[OPENAI_BASE] --from-literal=api_key=[OPENAI_KEY]`

:sparkles: Add support for deploying kai

---

bundle/manifests/konveyor-operator.clusterserviceversion.yaml
helm/templates/rbac/hub_role.yaml

Signed-off-by: Jason Montleon <jmontleo@redhat.com>
(cherry picked from commit 7961479537091efddd64975c66a4fa077ff8560e)

:sparkles: Remove SCC Permissions to run rootless (#382)

---

roles/tackle/templates/customresource-addon-analyzer.yml.j2
roles/tackle/templates/customresource-addon-tech-discovery.yml.j2

Following the _AnyUser_ change, the local m2 repository path needs to be set to /cache/m2 so the java provider will not use it's default path of /root/.m2.

:bug: Set the maven local repository path.

---

roles/tackle/templates/customresource-addon-analyzer.yml.j2
roles/tackle/templates/customresource-addon-tech-discovery.yml.j2

Pass the mavenCacheDir property to the java provider which is used to build the maven global settings needed by JDTLS.

:bug: set mavenCacheDir.

---

.github/actions/install-tackle/action.yml

Follow on to only add the auth to the install of tackle to actually test login in UI tests.

:sparkles: adding just auth to the install of tackle

---

bundle/manifests/konveyor-operator.clusterserviceversion.yaml
helm/templates/rbac/cluster_role.yaml
roles/tackle/tasks/main.yml
roles/tackle/templates/customresource-rhsso-keycloak.yml.j2

The reason for this is that there is a bug that causes the metrics/monitoring target to be broken and return a 404. Disabling it and cleaning up the servicemonitor is the best we can do to stop the noise right now. With RHBK there is no servicemonitor installed so nothing to do there.
https://issues.redhat.com/browse/RHSSO-1960

:bug: disable keycloak servicemonitor

---

roles/tackle/defaults/main.yml

The external access network policy allows 8080 and 8443. So using 8443 instead of 9443 allows everything to work.

:bug: Fix oauth to work with external access networkpolicy

---

roles/tackle/templates/networkpolicy.yml.j2

The servicemonitor endpoints are defined but inaccessible if monitoring is enabled on the namespace because we do not have a networkpolicy that allows access. RHBK has no servicemonitors, so in the case of RHBK there is nothing to do.

:bug: Add RHSSO servicemonitor networkpolicy

---

roles/tackle/tasks/kai.yml

If the key does not exist it will print a message:
```
TASK [Verify kai-api-key-secret has been created] *******************************************************************************************************************************************************************************************
ok: [localhost] => {
"msg": "Kai will not deploy until the credential secret exists. kubectl create secret -n konveyor generic kai-api-key-secret --fromliteral=genai_key=[BAM_KEY] --from-literal=api_base=[OPENAI_BASE] --from-literal=api_key=[OPENAI_KEY]\n"
}
PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost …
```

:sparkles: Add a log msg to clarify a secret is required to deploy kai

---

roles/tackle/templates/customresource-addon-tech-discovery.yml.j2

Related to: https://github.com/konveyor/tackle2-hub/pull/830

:ghost: Tech discovery should run at priority=1.
