konveyor/operator

- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- tackle-operator-catalog.yaml
Update operator images and links
> CSV: Update image to reflect quay.io locations

- README.md
- docs/k8s.md
- tackle-k8s.yaml
Add manifests and documentation in how to deploy in k8s
> Add k8s/minikube deployment instructions

- roles/tackle/templates/deployment-ui.yml.j2
Fixes https://github.com/konveyor/tackle2-operator/issues/7
> tackle-ui: Remove/consolidate env var.

- README.md
- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- tackle-operator-catalog.yaml
- watches.yaml
> Minor documentation and metadata updates

- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- Correct doc links to issues
- Remove extra ALM samples section
> CSV: Minor metadata updates

- roles/tackle/templates/configmap-hub-seed.yml.j2
> Seed proxies.

- roles/tackle/defaults/main.yml
Fixed 21, hub using the tackle-hub service account.
> fixed 21. Hub SA.

- README.md
> Add quay image status badge

- tools/tackle_cleanup.sh
- Add helper script to cleanup tackle deployments
> Add tackle cleanup script

- roles/tackle/templates/configmap-keycloak-sso.yml.j2
After looking at https://docs.google.com/document/d/1O0tQUoK5naowVpy67TB5RPEgfdEhgguUms2jFY3nJq0/edit 
the migrator user will need to create tasks in order to execute an analysis
> Add migrator to tasks:post scope for executing an analysis

- roles/tackle/templates/deployment-keycloak-sso.yml.j2
> Using quay.io/quay/busybox.

- bundle/manifests/tackle.konveyor.io_addons.yaml
- roles/tackle/defaults/main.yml
- roles/tackle/tasks/main.yml
- roles/tackle/templates/customresource-addon-windup.yml.j2
> Sync and update addons CRD

- README.md
- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- roles/tackle/defaults/main.yml
- roles/tackle/tasks/main.yml
- roles/tackle/templates/deployment-hub.yml.j2
- roles/tackle/templates/deployment-pathfinder.yml.j2
- roles/tackle/templates/deployment-ui.yml.j2
- roles/tackle/templates/secret-hub.yml.j2
- roles/tackle/templates/secret-webhook-server-secret.yml.j2
Fixes #33
Depends on:
- https://github.com/konveyor/tackle2-ui/pull/64
- https://github.com/konveyor/tackle-pathfinder/pull/212
The Tackle CR controlling variable is the feature_auth_required boolean (true by default)
> Implement single user changes (auth or noauth)

- roles/tackle/templates/configmap-keycloak-sso.yml.j2
Add missing scope declarations.
> Fix volumes scopes in keycloak realm.

- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- bundle/manifests/tackle.konveyor.io_addons.yaml
- roles/tackle/defaults/main.yml
- roles/tackle/tasks/main.yml
- roles/tackle/templates/customresource-addon-admin.yml.j2
- Create and configure admin addon CR
- Sync addon CRD to latest
- Fixes #53
> Introduce admin addon CR during deployment

- roles/tackle/defaults/main.yml
- roles/tackle/templates/ingress-ui.yml.j2
> Backport: proxy-body-size fix for beta.0

- roles/tackle/templates/configmap-keycloak-sso.yml.j2
Closes https://github.com/konveyor/tackle2-operator/issues/68
> Add missing migrator scopes to realm

- README.md
- Add instructions how to deploy using a beta or specially purposed
branch in README
> Add note regarding deployment on beta branches

- roles/tackle/templates/configmap-keycloak-sso.yml.j2
https://issues.redhat.com/browse/TACKLE-624
> TACKLE-624: Add migrator user to dependency:delete

- roles/tackle/templates/deployment-ui.yml.j2
- Loads an env var into the ui pod for determining file upload size. Helps to solve https://issues.redhat.com/browse/TACKLE-575
> Add entry for exposing upload size to the ui pod via env var

- roles/tackle/templates/configmap-keycloak-sso.yml.j2
https://issues.redhat.com/browse/TACKLE-604
> TACKLE-604: Add migrator to assessments scopes

- README.md
- tools/cut-release.py
- tools/templates/clusterserviceversion.yaml.j2
- tools/templates/tackle-k8s.yaml.j2
- Update documentation adding released versions or betas section
- Properly manage date for CSV templating and other minor fixes
- Sync CSV template with latest RBAC
> Update documentation and minor release tool fixes

- roles/tackle/templates/configmap-keycloak-sso.yml.j2
The _user_ role need for the hub to rev-proxy to pathfinder.
The :patch scope needed for assessment create/save.
> Add role named "user" to default roles.

- roles/tackle/templates/configmap-keycloak-sso.yml.j2
https://issues.redhat.com/browse/TACKLE-641
> TACKLE-641: Update realm for migrator regression 

- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- fixes OCP web console issue , see #91
> Pick #91 for v2.0.0

- tools/templates/clusterserviceversion.yaml.j2
- Sync release tools templates with latest changes
> Release tools sync templates

- README.md
- Include a note with warning regarding updates in between beta releases
> Update documentation regarding beta releases

- .gitignore
- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- tools/templates/clusterserviceversion.yaml.j2
- Update documentation links in CSV and other minor fixes
> Update documentation links

- .config/ansible-lint.yml
- .github/workflows/ansible-lint.yml
> Fix ansible-linter paths

- roles/tackle/defaults/main.yml
- roles/tackle/templates/route-ui.yml.j2
- See https://issues.redhat.com/projects/TACKLE/issues/TACKLE-682
> UI route enable re-direct by default

- bundle.Dockerfile
- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- tackle-k8s.yaml
- Initalize release v2.1.0 branch
> Initialize v2.1.0 release

- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- tools/templates/clusterserviceversion.yaml.j2
- Set pathfinder image to quay.io/konveyor/tackle-pathfinder:1.3.0-native
> Update pathfinder image

- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- tools/templates/clusterserviceversion.yaml.j2
> Backport #102 to v2.1.0

- roles/tackle/defaults/main.yml
- roles/tackle/templates/configmap-keycloak-sso.yml.j2
> Backport #105 to v2.1.0

- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- roles/tackle/defaults/main.yml
- tools/templates/clusterserviceversion.yaml.j2
> Backport #108 to v2.1.0

- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- roles/tackle/defaults/main.yml
- roles/tackle/templates/deployment-hub.yml.j2
- roles/tackle/templates/deployment-ui.yml.j2
- tools/templates/clusterserviceversion.yaml.j2
> Backport: pick #113

- .config/ansible-lint.yml
- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- roles/tackle/defaults/main.yml
- roles/tackle/tasks/main.yml
- roles/tackle/templates/deployment-hub.yml.j2
- roles/tackle/templates/deployment-keycloak-postgresql.yml.j2
- roles/tackle/templates/deployment-keycloak-sso.yml.j2
- roles/tackle/templates/deployment-pathfinder-postgresql.yml.j2
- roles/tackle/templates/deployment-pathfinder.yml.j2
- roles/tackle/templates/deployment-ui.yml.j2
- roles/tackle/templates/networkpolicy.yml.j2
- Remove all unused blocks, variables and logic from tackle role
- Fix "tackle" hard-coded instances in various resources
- Fix inconsistencies in naming for same objects between different resources
- Update deployment strategy defaults
> Operator Role Cleanup

- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- roles/tackle/defaults/main.yml
- roles/tackle/tasks/main.yml
- roles/tackle/templates/customresource-rhsso-clients.yml.j2
- roles/tackle/templates/customresource-rhsso-keycloak.yml.j2
- roles/tackle/templates/customresource-rhsso-realm.yml.j2
- roles/tackle/templates/customresource-rhsso-users.yml.j2
- roles/tackle/templates/deployment-hub.yml.j2
- roles/tackle/templates/deployment-pathfinder.yml.j2
- roles/tackle/templates/deployment-ui.yml.j2
- roles/tackle/templates/secret-hub.yml.j2
- tools/templates/clusterserviceversion.yaml.j2
> Backport: RHSSO support

- README.md
- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- tools/templates/clusterserviceversion.yaml.j2
- Update CSV and README to clarify requirement for RWX volumes
> Document RWX requirements

- README.md
- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- tools/templates/clusterserviceversion.yaml.j2
> Backport: Document RWX requirements

- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- tools/templates/clusterserviceversion.yaml.j2
> Backport: Upgrade pathfinder to v1.3.1

- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- tools/templates/clusterserviceversion.yaml.j2
> CSV minor updates

- bundle/manifests/tackle.konveyor.io_addons.yaml
Updates the addon CRD re: https://github.com/konveyor/tackle2-hub/pull/189. 
Signed-off-by: Jeff Ortel <jortel@redhat.com>
> Add an optional imagePullPolicy to the addon CRD.

- README.md
> Update documentation regarding RWX settings

- README.md
- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- roles/tackle/tasks/main.yml
- tools/templates/clusterserviceversion.yaml.j2
- Minor task naming fixes
- Updated RWX requirement comment in CSV metadata
- Removed last references of maven from README
> RWX CSV update and minor cleanups

- bundle.Dockerfile
- bundle/manifests/tackle-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- tackle-k8s.yaml
> Initialize v2.1.3 release

- roles/tackle/tasks/main.yml
> Backport: Ensure windup addon is always reconciled

- .github/workflows/publish.yml
Signed-off-by: Jason Montleon <jmontleo@redhat.com>
> :sparkles: Build operator+bundle using Composite GH Action

- .github/workflows/verifyPR.yml
Want to ensure that commits to this project conform to our title guidelines specified in https://github.com/konveyor/release-tools/blob/main/VERSIONING.md
> :seedling: Add PR checks

- .github/workflows/march-image-build-push.yml
- .github/workflows/publish.yml
- tools/konveyor-operator-publish-commands.sh
> :seedling: Action to automate publishing Konveyor operator releases

- .github/workflows/create-release.yml
Initial attempt at having a workflow that conducts a full "konveyor" release.
> :seedling: Create release workflow

- docs/installation-macos.md
> :book: Update Mac install instructions for Konveyor name change

- docs/installation-macos.md
Update tackle instance ns to konveyor ns
> :book: Update tackle instance ns to konveyor ns

- hack/install-tackle.sh
Also added ability to change the ingress class name
> :ghost: Update for konveyor-operator name change

- tools/konveyor-operator-publish-commands.sh
Signed-off-by: Jason Montleon <jmontleo@redhat.com>
(cherry picked from commit 0ee9dd2202fcacdec58172fa269b744ad8c8289c)
> :ghost: replace incorrect sed version replace

- roles/tackle/tasks/main.yml
I half-fixed the now-disabled var checks and did not undo my change, I should have caught that
> :bug: Fix typo from prior PR

- README.md
> :book: Update konveyor docs URL

- .github/workflows/create-release.yml
update konveyor/operator -> konveyor/tackle2-operator
> :bug: release-tooling: use the correct operator image

- .github/actions/install-tackle/action.yml
- .github/actions/make-bundle/action.yml
- .github/workflows/create-release.yml
- bundle/manifests/konveyor-operator.clusterserviceversion.yaml
- hack/install-tackle.sh
- helm/templates/deployment.yaml
- helm/values.yaml
- roles/tackle/defaults/main.yml
> :bug: tackle2-addon is no longer deployed

- .github/workflows/create-release.yml
> :ghost: don't wait for rulesets to build

- .github/workflows/pr-ci.yml
This reverts commit 71db73eefaf2dfa2bbe5da38b34aea6b320ddad2.
> :bug: Revert ":seedling: double the ttl on operator image (#329)"

- .github/workflows/pr-ci.yml
> :bug: build the bundle before build+push

- .github/actions/make-bundle/action.yml
- .github/workflows/create-release.yml
- hack/install-konveyor.sh
- roles/tackle/templates/customresource-addon-language-discovery.yml.j2
- roles/tackle/templates/customresource-addon-tech-discovery.yml.j2
Reverts:
- https://github.com/konveyor/operator/pull/348
- https://github.com/konveyor/operator/pull/347
- https://github.com/konveyor/operator/pull/346
> Revert 0.5

- roles/tackle/defaults/main.yml
related to https://github.com/konveyor/java-analyzer-bundle/pull/106
> :bug: reducing requests and limits after we have better control of the JVM

- roles/tackle/templates/customresource-addon-analyzer.yml.j2
Set `mavenInsecure` based on customer settings.
> :bug: Maven insecure

- roles/tackle/templates/customresource-addon-analyzer.yml.j2
Set `mavenInsecure` based on customer settings.
backport: https://github.com/konveyor/operator/pull/397 to release-0.6
---------
> :bug: Maven insecure (#397)

- Dockerfile
- molecule/default/molecule.yml
- molecule/kind/molecule.yml
- requirements.yml
Update to operator-sdk 1.37.1
Changes are based on documentation at:
https://docs.openshift.com/container-platform/4.15/operators/operator_sdk/ansible/osdk-ansible-updating-projects.html
https://docs.openshift.com/container-platform/4.17/operators/operator_sdk/ansible/osdk-ansible-updating-projects.html
> :sparkles: Update to Operator SDK 1.37.1

- roles/tackle/templates/customresource-extension.yml.j2
Re: https://issues.redhat.com/browse/MTA-5003
> :bug: Fix lspServerName in nodejs extenson.

- .github/workflows/create-release.yml
https://github.com/konveyor/ci/issues/83
> :seedling: Update create-release.yml ubuntu-24.04

- .github/workflows/march-image-build-push.yml
https://github.com/konveyor/ci/issues/83
> :seedling: Update march-image-build-push.yml ubuntu-24.04

- .github/workflows/create-release.yml
https://github.com/konveyor/ci/issues/83
> :seedling: Update create-release.yml ubuntu-latest

- Makefile
(cherry picked from commit 392d8c450812b36d69b4869a5f90bad5a97ebe63)
> :ghost: Add distro prefix for linux oc client download

- .github/workflows/create-release.yml
(cherry picked from commit 67e27c2e96e622d8cb1badcd63ad5e2eec361211)
> :ghost: Update path in case of downloaded binaries

- bundle/manifests/tackle.konveyor.io_schemas.yaml
`git add` generated schema manifest.
> :bug: Add generated bundle.
